#!/usr/bin/env python3
"""Generate docs/CODEMAP.md — a compact index of every module, class, and function.

Gives agents (and humans) a single file that answers "what is where, what goes
where, who imports what" without burning tokens on grep hunting.

Usage:
    python scripts/codemap.py                 # write docs/CODEMAP.md
    python scripts/codemap.py --stdout        # print instead of writing
    python scripts/codemap.py --grep NAME     # find NAME across the map, with context

Stdlib only (ast + pathlib). Run `make codemap` after adding/moving code and
commit the regenerated map with the change.
"""

from __future__ import annotations

import argparse
import ast
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIRS = ["src/finetune_studio", "scripts", "tests"]
OUTPUT = ROOT / "docs" / "CODEMAP.md"
MAX_LINE = 79  # signature display cap


@dataclass
class Symbol:
    name: str
    kind: str  # class | def
    signature: str
    lineno: int
    doc: str  # first line of docstring, may be empty
    children: list[Symbol] = field(default_factory=list)


def _fmt_args(node: ast.AST) -> str:
    a = node.args  # type: ignore[attr-defined]
    parts: list[str] = []

    def fmt(arg: ast.arg, default: ast.expr | None = None) -> str:
        s = arg.arg
        if arg.annotation is not None:
            s += f": {ast.unparse(arg.annotation)}"
        if default is not None:
            s += f" = {ast.unparse(default)}"
        return s

    pos = list(a.posonlyargs) + list(a.args)
    defaults: list[ast.expr | None] = [None] * (len(pos) - len(a.defaults)) + list(a.defaults)
    parts += [fmt(p, d) for p, d in zip(pos, defaults)]
    if a.vararg:
        parts.append(f"*{fmt(a.vararg)}")
    elif a.kwonlyargs:
        parts.append("*")
    parts += [fmt(k, d) for k, d in zip(a.kwonlyargs, a.kw_defaults)]
    if a.kwarg:
        parts.append(f"**{fmt(a.kwarg)}")
    sig = ", ".join(parts)
    ret = ""
    if node.returns is not None:  # type: ignore[attr-defined]
        ret = f" -> {ast.unparse(node.returns)}"
    out = f"({sig}){ret}"
    if len(out) > MAX_LINE:
        out = out[: MAX_LINE - 1] + "…"
    return out


def _first_doc_line(node: ast.AST) -> str:
    doc = ast.get_docstring(node)
    if not doc:
        return ""
    line = doc.strip().splitlines()[0]
    return line[:100]


def _walk_node(node: ast.AST, prefix: str = "") -> list[Symbol]:
    symbols: list[Symbol] = []
    for child in ast.iter_child_nodes(node):
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
            kind = "async def" if isinstance(child, ast.AsyncFunctionDef) else "def"
            symbols.append(
                Symbol(child.name, kind, _fmt_args(child), child.lineno, _first_doc_line(child))
            )
        elif isinstance(child, ast.ClassDef):
            cls = Symbol(
                child.name,
                "class",
                f"({', '.join(ast.unparse(b) for b in child.bases)})" if child.bases else "",
                child.lineno,
                _first_doc_line(child),
                children=_walk_node(child, prefix=f"{prefix}{child.name}."),
            )
            symbols.append(cls)
    return symbols


def parse_file(path: Path) -> tuple[list[Symbol], list[str]]:
    """Return (top-level symbols, import sources)."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
    except SyntaxError as e:
        return [Symbol("!! SYNTAX ERROR !!", "def", str(e), 0, "")], []

    symbols = _walk_node(tree)
    imports: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imports.add(node.module)
    return symbols, sorted(i for i in imports if i.startswith("finetune_studio"))


def collect() -> dict[str, tuple[list[Symbol], list[str], int]]:
    result: dict[str, tuple[list[Symbol], list[str], int]] = {}
    for src in SRC_DIRS:
        for path in sorted((ROOT / src).rglob("*.py")):
            if "__pycache__" in path.parts:
                continue
            syms, imports = parse_file(path)
            lines = len(path.read_text(encoding="utf-8", errors="replace").splitlines())
            result[str(path.relative_to(ROOT))] = (syms, imports, lines)
    return result


def render(files: dict[str, tuple[list[Symbol], list[str], int]]) -> str:
    out: list[str] = [
        "# CODEMAP — what is where (auto-generated, do not hand-edit)",
        "",
        "Generated by `make codemap` (`scripts/codemap.py`). Regenerate and commit",
        "whenever you add/move/rename modules or functions.",
        "",
        "Rules for agents: consult this file BEFORE hunting for symbols; put new code",
        "in the module that already owns that concern (see AGENTS.md); one concern per module.",
        "",
    ]

    by_top: dict[str, list[str]] = defaultdict(list)
    for rel in sorted(files):
        top = rel.split("/")[1] if rel.startswith("src/") else rel.split("/")[0]
        by_top[top].append(rel)

    out.append("## Quick stats")
    total_lines = sum(n for _, _, n in files.values())
    out.append(f"{len(files)} files · {total_lines} lines")
    for top, rels in sorted(by_top.items()):
        lines = sum(files[r][2] for r in rels)
        out.append(f"- `{top}`: {len(rels)} files, {lines} lines")
    out.append("")

    for top, rels in sorted(by_top.items()):
        out.append(f"\n# {top}\n")
        for rel in rels:
            syms, imports, lines = files[rel]
            out.append(f"## `{rel}` ({lines} lines)")
            if not syms or all(s.name.startswith("_") and s.kind == "def" and not s.doc for s in syms) and len(syms) < 3 and not any(s.kind != "def" for s in syms):
                pass  # still show, tiny modules matter too
            for s in syms:
                deco = s.kind
                head = f"- `{deco} {s.name}{s.signature}` (L{s.lineno})"
                if s.kind == "class":
                    out.append(f"- `class {s.name}{s.signature}` (L{s.lineno})")
                    for c in s.children:
                        out.append(f"  - `{c.kind} {c.name}{c.signature}` (L{c.lineno})")
                else:
                    suffix = f" — {s.doc}" if s.doc else ""
                    out.append(f"- `{s.name}{s.signature}` (L{s.lineno}){suffix}")
            if imports:
                out.append(f"  - imports: {', '.join(imports)}")
            out.append("")

    return "\n".join(out)


def grep_map(files: dict[str, tuple[list[Symbol], list[str], int]], needle: str) -> str:
    """Return map lines whose file/symbol names contain needle (case-insensitive)."""
    n = needle.lower()
    hits: list[str] = []

    def walk(syms: list[Symbol], rel: str, depth: int = 0) -> None:
        for s in syms:
            if n in s.name.lower() or n in rel.lower():
                hits.append(f"{rel}:{s.lineno}  {s.kind} {s.name}{s.signature}")
            walk(s.children, rel, depth + 1)

    for rel, (syms, _, _) in sorted(files.items()):
        walk(syms, rel)
    return "\n".join(hits) if hits else f"no symbol or file matches '{needle}'"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stdout", action="store_true", help="print instead of writing docs/CODEMAP.md")
    ap.add_argument("--grep", metavar="NAME", help="find NAME in the map instead of writing it")
    args = ap.parse_args()

    files = collect()
    if args.grep:
        print(grep_map(files, args.grep))
        return
    md = render(files)
    if args.stdout:
        print(md)
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(md, encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(md.splitlines())} lines, {len(files)} files)")


if __name__ == "__main__":
    main()
