#!/usr/bin/env bash
# Finetune Studio — legacy launcher that reads port from user settings.
# The canonical user unit is generated by the repository-root install-service.sh.

set -euo pipefail

SETTINGS="$HOME/.finetune-studio/settings.json"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORT=7860
HOST="0.0.0.0"

if [[ -f "$SETTINGS" ]]; then
    # Use python to parse JSON (jq may not be installed)
    read -r PORT HOST < <(python3 -c "
import json
with open('$SETTINGS') as f:
    s = json.load(f)
print(s.get('port', 7860), s.get('host', '0.0.0.0'))
")
fi

cd "$REPO_DIR"
PYTHON="$REPO_DIR/.venv/bin/python"
if [[ ! -x "$PYTHON" ]]; then
    echo "[run] ERROR: project venv missing at $PYTHON; run bash install.sh first." >&2
    exit 1
fi

exec "$PYTHON" -m uvicorn finetune_studio.webui.app:app \
    --host "$HOST" --port "$PORT" --no-access-log
